### ISSUE TITLE
Windows not Showing

### ISSUE THREAD

**Issue by johntom** [gitterHQ/desktop#69]
Hi,
1. I was using gitter.exe on a 64bit win7 computer for about 2 weeks.
2. At some point the windows would not show in expanded mode. Each instance shows in task bar with a thumbnail of image, but when I click nothing displays.
3. All is proper in the system tray
4. I've uninstalled/re-installed and checked the registry
Any ideas on how to fix?
TIA
John

**Comment by mydigitalself** [comment]
Hey there,

Silly question, but don't suppose the window has decided to move itself to another desktop or a strange position out of view on your desktop? Have seen this once before...

**Comment by johntom** [comment]
Not silly at all but I only have a single monitor setup. I was looking for a position in registry but did not locate and have not idea on how to fix.

J

**Comment by mydigitalself** [comment]
Forgive my naivety, haven't used Windows intensively for a long time, but on Mac you can have multiple virtual desktops and I've seen the Mac client do this once before where it opens the app on a different virtual desktop for some bizarre reason. Given the Mac & Windows app are built on the same core (nw.js) I was wondering if that could happen at all. So you may not have additional physical desktops, but it may have put it onto a virtual one.

**Comment by johntom** [comment]
I have only 1 physical display device. Is there a setting kept in registry?

**Comment by MadLittleMods** [comment]
Can you try to use `win + right` or `win + left` to try to snap the window onto your screen?

---

## Super sleuth nw.js dev tools solution

Open dev tools. Oh wait, I assume you can't because the window is not showing and it is in the top bar menu. **But there is still hope**, you can use the remote debugger.

Close out Gitter completely and open a new instance through the CMD prompt. *You can find the path to the Gitter.exe via your shortcut.*

`C:\Users\madli_000\AppData\Local\Programs\Gitter\Gitter.exe --remote-debugging-port=1234`

Visit `http://localhost:1234/` and you should see "Inspectable WebContents" with some entries. I am curious to know if you have 1 or 2 "Gitter" links there.

![](http://i.imgur.com/IyJzzYQ.png)

Click on the only "Gitter" link there and it should bring up some webkit dev tools(just like Chrome).

Switch to the "Console" tab. *If the input at the bottom is messed up, switch to another tab and come back. The input at the bottom got messed up for every command I entered.*

Enter the following to open the main Chat window:

```
gui.Window.get(
	window.open('loggedin.html', {
		focus: true
	});
);
```

The chat window should appear. If the window appears then you are all good.

If the window is not showing, visit `http://localhost:1234/` again. Does it have two entries now? Open the non-visited link and run the following command to move the window into view and set a size.

```
var gui = window.require('nw.gui');
var win = gui.Window.get();

win.moveTo(0, 0);
win.resizeTo(500, 500);
```

**Comment by johntom** [comment]
Wow, am I impressed it worked!

Thanks so much

John

**Comment by MadLittleMods** [comment]
@johntom Awesome! I am glad it worked :smiley: 

I am curious to know how far you had to follow the steps (but no worries if you don't follow-up):
 - Was the window visible after doing `window.open('loggedin.html', { focus: true });`?
 - Or only after moving/resizing?
 - How many entries in the remote debugger did you have initially?

**Comment by androidformax** [comment]
Im make the video to russian users.
enjoy https://youtu.be/Bj8J9QT2eVk

**Comment by lukka** [comment]
worked for me too, thanks @MadLittleMods !

**Comment by Oluwasetemi** [comment]
@MadLittleMods 
```js
gui.Window.get(
    window.open('loggedin.html', {
        focus: true
    });
);
```
seems not to work for me.

**Comment by MadLittleMods** [comment]
@Oluwasetemi Have you tried the second part? "If the window is not showing"

**Comment by Oluwasetemi** [comment]
@MadLittleMods yes it did not respond as well.

**Comment by Oluwasetemi** [comment]
I just resolved it ! 
Note: after using the localhost:1234, the ![image](https://gmkr.io/s/5794b18c718651e2654d548e/0)

![dev tool](https://gmkr.io/s/5794b2fdd53364db78266bc4/0)

:+1:  to @MadLittleMods and @gitter twitter channel

**Comment by Oluwasetemi** [comment]
@MadLittleMods will I have to do this on every start up of gitter.

**Comment by MadLittleMods** [comment]
@Oluwasetemi Most likely, you won't need to run through these steps again.
